// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/admin/[...catchall].tsx";
import * as $2 from "./routes/api/companies.ts";
import * as $3 from "./routes/styles.css.ts";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/CompaniesBackToTop.tsx";
import * as $$2 from "./islands/CompaniesFloatingButton.tsx";
import * as $$3 from "./islands/CompaniesFooter.tsx";
import * as $$4 from "./islands/CompaniesFormField.tsx";
import * as $$5 from "./islands/CompaniesHeader.tsx";
import * as $$6 from "./islands/CompaniesList.tsx";
import * as $$7 from "./islands/CompaniesModals.tsx";
import * as $$8 from "./islands/CompaniesNominateForm.tsx";
import * as $$9 from "./islands/CompaniesScrollBar.tsx";
import * as $$10 from "./islands/DragAndDropImageZone.tsx";
import * as $$11 from "./islands/HeaderButton.tsx";
import * as $$12 from "./islands/HeaderModals.tsx";
import * as $$13 from "./islands/HeaderSearchbar.tsx";
import * as $$14 from "./islands/Newsletter.tsx";
import * as $$15 from "./islands/OutOfStock.tsx";
import * as $$16 from "./islands/ProductImageZoom.tsx";
import * as $$17 from "./islands/SearchControls.tsx";
import * as $$18 from "./islands/ShippingSimulation.tsx";
import * as $$19 from "./islands/SliderJS.tsx";
import * as $$20 from "./islands/Toast.tsx";
import * as $$21 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/admin/[...catchall].tsx": $1,
    "./routes/api/companies.ts": $2,
    "./routes/styles.css.ts": $3,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/CompaniesBackToTop.tsx": $$1,
    "./islands/CompaniesFloatingButton.tsx": $$2,
    "./islands/CompaniesFooter.tsx": $$3,
    "./islands/CompaniesFormField.tsx": $$4,
    "./islands/CompaniesHeader.tsx": $$5,
    "./islands/CompaniesList.tsx": $$6,
    "./islands/CompaniesModals.tsx": $$7,
    "./islands/CompaniesNominateForm.tsx": $$8,
    "./islands/CompaniesScrollBar.tsx": $$9,
    "./islands/DragAndDropImageZone.tsx": $$10,
    "./islands/HeaderButton.tsx": $$11,
    "./islands/HeaderModals.tsx": $$12,
    "./islands/HeaderSearchbar.tsx": $$13,
    "./islands/Newsletter.tsx": $$14,
    "./islands/OutOfStock.tsx": $$15,
    "./islands/ProductImageZoom.tsx": $$16,
    "./islands/SearchControls.tsx": $$17,
    "./islands/ShippingSimulation.tsx": $$18,
    "./islands/SliderJS.tsx": $$19,
    "./islands/Toast.tsx": $$20,
    "./islands/WishlistButton.tsx": $$21,
  },
  baseUrl: import.meta.url,
};

export default manifest;
